# Generated by Django 3.1.7 on 2021-04-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ImageField(choices=[(1, 'Order confirmed'), (2, 'Picked by courier'), (3, 'On the way'), (4, 'Delivered'), (5, 'Processing Your Order')], default=5, upload_to=''),
        ),
    ]
