# Generated by Django 3.1.7 on 2021-04-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0003_auto_20210425_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Order confirmed'), (2, 'Picked by courier'), (3, 'On the way'), (4, 'Delivered'), (5, 'Processing Your Order')], default='Processing Your Order', max_length=50),
        ),
    ]
