# Generated by Django 3.1.7 on 2021-04-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0004_auto_20210425_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Picked by courier', 'Picked by courier'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Processing Your Order', 'Processing Your Order')], default='Processing Your Order', max_length=50),
        ),
    ]
