# Generated by Django 3.1.7 on 2021-04-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'Billing Adrresses'},
        ),
    ]
