# Generated by Django 3.1.7 on 2021-04-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imagge',
            new_name='image',
        ),
    ]
